---
- name: Ensure that Git is installed
  apt:
    name: git
    state: present

- name: modify .bashrc
  blockinfile:
    dest: "{{home_dir}}/.bashrc"
    block: |
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
      export PATH=$GOBIN:$PATH:/usr/local/go/bin
    marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
    insertafter: EOF
    create: yes 

- name: Clone the Gaia repository
  ansible.builtin.git:
    repo: https://github.com/cosmos/gaia
    dest: /tmp/ansible/gaia
    single_branch: yes
    version: v4.2.0

- name: Install gaia
  shell:
    cmd: |
        source ~/.bashrc && make install
        gaiad init chooseanicehandle
    chdir: /tmp/ansible/gaia
  args:
      executable: /bin/bash

- name: Download genesis.cosmoshub-4.json
  get_url:
    url: https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz
    dest: ./genesis.cosmoshub-4.json.gz
    mode: '0440'

- name: Unzip the genesis.cosmoshub-4.json file
  ansible.builtin.shell:
    cmd: |
        gzip -d genesis.cosmoshub-4.json.gz
        mv genesis.cosmoshub-4.json ~/.gaia/config/genesis.json

- name: Start gaiad
  ansible.builtin.shell:
    cmd: gaiad start --p2p.seeds bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656 --x-crisis-skip-assert-invariants