---
- name: Install Golang
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    new_go_version: 1.17.6
    home_dir: "/root"
    file_owner: figment
  tasks:
  - name: check current golang version
    command: bash -c "/usr/local/go/bin/go version|sed -e 's/go version go//g'|cut -d' ' -f1"
    ignore_errors: true
    register: go_version
    changed_when: false

  - name: download golang tar 
    get_url:
      url: "https://storage.googleapis.com/golang/go{{new_go_version}}.linux-amd64.tar.gz"
      dest: "{{home_dir}}"
      mode: 0440
      
  - name: Remove old installation of Go
    file:
      path: /usr/local/go
      state: absent
    become: true

  - name: Extract the Go tarball
    unarchive:
      src: "{{home_dir}}/go{{new_go_version}}.linux-amd64.tar.gz"
      dest: /usr/local
      copy: no
    become: true

  - name: create go directories in home
    file:
      path: "{{item}}"
      state: directory
      owner: "{{file_owner}}"
      group: "{{file_owner}}"
      mode: 0775
    with_items:
    - "{{home_dir}}/go"
    - "{{home_dir}}/go/bin"
      
  - name: modify .bashrc
    blockinfile:
      dest: "{{home_dir}}/.bashrc"
      block: |
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$GOBIN:$PATH:/usr/local/go/bin
      marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
      insertafter: EOF
      create: yes 

  - name: Source .bashrc file
    shell: source ~/.bashrc && ls
    args:
      executable: /bin/bash